### ISSUE TITLE
Some questions about making detector dataset

### ISSUE THREAD

**Issue by slimhappy** [tancik/StegaStamp#26]
Hello, tancik !
    I am keen on your outstanding work. But when I was traing a detector for distiguishing the encoded images from complex background (not totally white), I have some trouble about making dataset. Here is my questions:
1. Are the encoded images placing on totally white background in the traing dataset for detector?
2. If the encoded image's size is small (maybe 1/100 of an A4 paper), how can I make a training dataset to get great precision ?
   
   Finally, I have written a [documentation](https://github.com/slimhappy/Stegastamp_Readme) to guide chinese novices to build an environment and turn your code from tensorflow 1.x to tensorflow 2.x.  I hope you will like it and it can help more githubers to run your work.

**Comment by ggohem** [comment]
> Hello, tancik !
> I am keen on your outstanding work. But when I was traing a detector for distiguishing the encoded images from complex background (not totally white), I have some trouble about making dataset. Here is my questions:
> 
> 1. Are the encoded images placing on totally white background in the traing dataset for detector?
> 2. If the encoded image's size is small (maybe 1/100 of an A4 paper), how can I make a training dataset to get great precision ?
>    Finally, I have written a [documentation](https://github.com/slimhappy/Stegastamp_Readme) to guide chinese novices to build an environment and turn your code from tensorflow 1.x to tensorflow 2.x.  I hope you will like it and it can help more githubers to run your work.

Hey, is this problem solved?@slimhappy

**Comment by slimhappy** [comment]
> > Hello, tancik !
> > I am keen on your outstanding work. But when I was traing a detector for distiguishing the encoded images from complex background (not totally white), I have some trouble about making dataset. Here is my questions:
> > 
> > 1. Are the encoded images placing on totally white background in the traing dataset for detector?
> > 2. If the encoded image's size is small (maybe 1/100 of an A4 paper), how can I make a training dataset to get great precision ?
> >    Finally, I have written a [documentation](https://github.com/slimhappy/Stegastamp_Readme) to guide chinese novices to build an environment and turn your code from tensorflow 1.x to tensorflow 2.x.  I hope you will like it and it can help more githubers to run your work.
> 
> Hey, is this problem solved?@slimhappy

Not yet

**Comment by ggohem** [comment]
Hello, I received a reply from the author as follows:

&nbsp;

&nbsp;

&nbsp;

''&nbsp; I don't remember exactly how large the transformations were, I just chose a value that matched what I wanted to recover in the real-world. In fact the detector is just learning how to pick out an image on another image. I found that training it on just square images (not stegastamped) pasted on a large image worked just as well. Because of the error detection when decoding the stegastamp it is fine if the detector isn't perfect. There is a lot that could be explored to make the detector better including end-to-end training. I am excited to see if someone pursues this direction. ''

&nbsp;

&nbsp;

&nbsp;

You can have a ***@***.***



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tancik/StegaStamp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 中午11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tancik/StegaStamp] Some questions about making detector dataset (#26)





   
Hello, tancik !
 I am keen on your outstanding work. But when I was traing a detector for distiguishing the encoded images from complex background (not totally white), I have some trouble about making dataset. Here is my questions:
  
Are the encoded images placing on totally white background in the traing dataset for detector?
 
If the encoded image's size is small (maybe 1/100 of an A4 paper), how can I make a training dataset to get great precision ?
 Finally, I have written a documentation to guide chinese novices to build an environment and turn your code from tensorflow 1.x to tensorflow 2.x.  I hope you will like it and it can help more githubers to run your work.
   
Hey, is this problem ***@***.***
  
Not yet
